# Generated by Django 5.1.7 on 2025-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=255, null=True),
        ),
    ]
