# Generated by Django 5.1.7 on 2025-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_content', models.TextField()),
                ('story_title', models.CharField(default='Our Story', max_length=200)),
                ('story_content', models.TextField()),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_content', models.TextField()),
                ('values_title', models.CharField(default='Our Values', max_length=200)),
                ('values_content', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('story_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('icon', models.CharField(help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
